apiVersion: v1
data:
  default-tasks: |-
    [
      {
        "name": "compact-blobstore-default",
        "cron": "0 0 9 * * ?",
        "typeId": "blobstore.compact",
        "taskProperties": {
          "blobstoreName": "default"
        }
      },
      {
        "name": "compact-blobstore-npm",
        "cron": "0 20 9 * * ?",
        "typeId": "blobstore.compact",
        "taskProperties": {
          "blobstoreName": "npm"
        }
      },
      {
        "name": "purge-unused-components-and-assets",
        "cron": "0 40 9 * * ?",
        "typeId": "repository.purge-unused",
        "taskProperties": {
          "repositoryName": "*",
          "lastUsed": "14"
        }
      },
      {
        "name": "purge-orphaned-api-keys",
        "cron": "0 0 10 * * ?",
        "typeId": "security.purge-api-keys"
      },
      {
        "name": "purge-unused-maven-snapshot-versions",
        "cron": "0 20 10 * * ?",
        "typeId": "repository.maven.purge-unused-snapshots",
        "taskProperties": {
          "repositoryName": "*",
          "lastUsed": "14"
        }
      },
      {
        "name": "remove-maven-indexes",
        "cron": "0 40 10 * * ?",
        "typeId": "repository.maven.unpublish-dotindex",
        "taskProperties": {
          "repositoryName": "*"
        }
      },
      {
        "name": "remove-snapshots-from-maven-repository",
        "cron": "0 0 11 * * ?",
        "typeId": "repository.maven.remove-snapshots",
        "taskProperties": {
          "repositoryName": "*",
          "minimumRetained": "1",
          "snapshotRetentionDays": "30",
          "gracePeriodInDays": "10"
        }
      },
      {
        "name": "rebuild-maven-repository-metadata",
        "cron": "0 20 11 * * ?",
        "typeId": "repository.maven.rebuild-metadata",
        "taskProperties": {
          "repositoryName": "*"
        }
      },
      {
        "name": "rebuild-repository-index",
        "cron": "0 40 11 * * ?",
        "typeId": "repository.rebuild-index",
        "taskProperties": {
          "repositoryName": "*"
        }
      }
    ]
kind: ConfigMap
metadata:
  labels:
    app: nexus
  name: nexus-default-tasks