apiVersion: v1
data:
  default-users: |-
    [
      {
        "username": "ci.user",
        "first_name": "ci.user",
        "last_name": "CI",
        "email": "ci.user@edp.com",
        "password": "",
        "roles": [
          "edp-admin"
        ]
      }
    ]
kind: ConfigMap
metadata:
  labels:
    app: nexus
  name: nexus-default-users