apiVersion: v1
data:
  default-capabilities: |-
    [
      {
        "capability_typeId": "rutauth",
        "capability_properties": {
          "httpHeader": "X-Auth-Userid"
        }
      }
    ]
kind: ConfigMap
metadata:
  labels:
    app: nexus
  name: nexus-default-capabilities