with-expecter: True
inpackage: False
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName | lower}}_mock.go"
all: True
issue-845-fix: True
packages:
  github.com/epam/edp-nexus-operator/pkg/client/nexus:
    config:
      recursive: True
