{{- if .Values.oauth2_proxy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nexus-proxy
    {{- include "nexus-operator.labels" . | nindent 4 }}
  name: nexus-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nexus-proxy.selectorLabels" . | indent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/oauth2-proxy/configmap.yaml") . | sha256sum }}
      labels:
        app: nexus-proxy
        {{- include "nexus-proxy.selectorLabels" . | indent 8 }}
    spec:
      serviceAccountName: nexus-proxy
      containers:
        - name: nexus-proxy
          image: "{{ .Values.oauth2_proxy.image.repository }}:{{ .Values.oauth2_proxy.image.tag  }}"
          args:
            - --http-address=0.0.0.0:4180
            - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
          {{- if kindIs "map" .Values.oauth2_proxy.extraArgs }}
            {{- range $key, $value := .Values.oauth2_proxy.extraArgs }}
            {{- if $value }}
            - --{{ $key }}={{ tpl ($value | toString) $ }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
            {{- end }}
          {{- end }}
          env:
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                # keycloak-client-nexus-secret is created by keycloak-operator
                secretKeyRef:
                  name:  keycloak-client-nexus-secret
                  key: clientSecret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oauth2_proxy.existingSecret.secretName }}
                  key: {{ .Values.oauth2_proxy.existingSecret.secretKey }}

          {{- if .Values.oauth2_proxy.extraEnv }}
  {{ tpl (toYaml .Values.oauth2_proxy.extraEnv) . | indent 10 }}
          {{- end }}
          ports:
            - containerPort: 4180
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            timeoutSeconds: 5
            successThreshold: 1
            periodSeconds: 10
          resources:
{{ toYaml .Values.oauth2_proxy.resources | indent 12 }}
          volumeMounts:
            - mountPath: /etc/oauth2_proxy/oauth2_proxy.cfg
              name: configmain
              subPath: oauth2_proxy.cfg
          {{- if .Values.oauth2_proxy.extraVolumeMounts }}
            {{- toYaml .Values.oauth2_proxy.extraVolumeMounts | nindent 12 }}
          {{- end }}
      volumes:
        - configMap:
            defaultMode: 420
            name: nexus-proxy-config
          name: configmain
      {{- if .Values.oauth2_proxy.extraVolumes }}
        {{- toYaml .Values.oauth2_proxy.extraVolumes | nindent 8 }}
      {{- end }}

    {{- if .Values.oauth2_proxy.affinity }}
      affinity:
{{ toYaml .Values.oauth2_proxy.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.oauth2_proxy.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.oauth2_proxy.nodeSelector | indent 8 }}
    {{- end }}
      tolerations:
{{ toYaml .Values.oauth2_proxy.tolerations | indent 8 }}
{{ end }}
