apiVersion: edp.epam.com/v1alpha1
kind: Nexus
metadata:
  name: nexus-sample
spec:
  url: http://host.containers.internal:9085/
  secret: nexus-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
data:
  user: YWRtaW4=
  password: YWRtaW4=
