---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: placeholder
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - nexusblobstores
  - nexuscleanuppolicies
  - nexuses
  - nexusrepositories
  - nexusroles
  - nexusscripts
  - nexususers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - nexusblobstores/finalizers
  - nexuscleanuppolicies/finalizers
  - nexuses/finalizers
  - nexusrepositories/finalizers
  - nexusroles/finalizers
  - nexusscripts/finalizers
  - nexususers/finalizers
  verbs:
  - update
- apiGroups:
  - edp.epam.com
  resources:
  - nexusblobstores/status
  - nexuscleanuppolicies/status
  - nexuses/status
  - nexusrepositories/status
  - nexusroles/status
  - nexusscripts/status
  - nexususers/status
  verbs:
  - get
  - patch
  - update
