//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AptHosted) DeepCopyInto(out *AptHosted) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AptHosted.
func (in *AptHosted) DeepCopy() *AptHosted {
	if in == nil {
		return nil
	}
	out := new(AptHosted)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AptHostedRepository) DeepCopyInto(out *AptHostedRepository) {
	*out = *in
	in.HostedSpec.DeepCopyInto(&out.HostedSpec)
	out.Apt = in.Apt
	in.AptSigning.DeepCopyInto(&out.AptSigning)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AptHostedRepository.
func (in *AptHostedRepository) DeepCopy() *AptHostedRepository {
	if in == nil {
		return nil
	}
	out := new(AptHostedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AptProxy) DeepCopyInto(out *AptProxy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AptProxy.
func (in *AptProxy) DeepCopy() *AptProxy {
	if in == nil {
		return nil
	}
	out := new(AptProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AptProxyRepository) DeepCopyInto(out *AptProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
	out.Apt = in.Apt
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AptProxyRepository.
func (in *AptProxyRepository) DeepCopy() *AptProxyRepository {
	if in == nil {
		return nil
	}
	out := new(AptProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AptSigning) DeepCopyInto(out *AptSigning) {
	*out = *in
	if in.Passphrase != nil {
		in, out := &in.Passphrase, &out.Passphrase
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AptSigning.
func (in *AptSigning) DeepCopy() *AptSigning {
	if in == nil {
		return nil
	}
	out := new(AptSigning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AptSpec) DeepCopyInto(out *AptSpec) {
	*out = *in
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(AptProxyRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Hosted != nil {
		in, out := &in.Hosted, &out.Hosted
		*out = new(AptHostedRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AptSpec.
func (in *AptSpec) DeepCopy() *AptSpec {
	if in == nil {
		return nil
	}
	out := new(AptSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Bower) DeepCopyInto(out *Bower) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bower.
func (in *Bower) DeepCopy() *Bower {
	if in == nil {
		return nil
	}
	out := new(Bower)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BowerGroupRepository) DeepCopyInto(out *BowerGroupRepository) {
	*out = *in
	in.GroupSpec.DeepCopyInto(&out.GroupSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BowerGroupRepository.
func (in *BowerGroupRepository) DeepCopy() *BowerGroupRepository {
	if in == nil {
		return nil
	}
	out := new(BowerGroupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BowerHostedRepository) DeepCopyInto(out *BowerHostedRepository) {
	*out = *in
	in.HostedSpec.DeepCopyInto(&out.HostedSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BowerHostedRepository.
func (in *BowerHostedRepository) DeepCopy() *BowerHostedRepository {
	if in == nil {
		return nil
	}
	out := new(BowerHostedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BowerProxyRepository) DeepCopyInto(out *BowerProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
	out.Bower = in.Bower
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BowerProxyRepository.
func (in *BowerProxyRepository) DeepCopy() *BowerProxyRepository {
	if in == nil {
		return nil
	}
	out := new(BowerProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BowerSpec) DeepCopyInto(out *BowerSpec) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(BowerGroupRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(BowerProxyRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Hosted != nil {
		in, out := &in.Hosted, &out.Hosted
		*out = new(BowerHostedRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BowerSpec.
func (in *BowerSpec) DeepCopy() *BowerSpec {
	if in == nil {
		return nil
	}
	out := new(BowerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cleanup) DeepCopyInto(out *Cleanup) {
	*out = *in
	if in.PolicyNames != nil {
		in, out := &in.PolicyNames, &out.PolicyNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cleanup.
func (in *Cleanup) DeepCopy() *Cleanup {
	if in == nil {
		return nil
	}
	out := new(Cleanup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoapodsProxyRepository) DeepCopyInto(out *CocoapodsProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoapodsProxyRepository.
func (in *CocoapodsProxyRepository) DeepCopy() *CocoapodsProxyRepository {
	if in == nil {
		return nil
	}
	out := new(CocoapodsProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CocoapodsSpec) DeepCopyInto(out *CocoapodsSpec) {
	*out = *in
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(CocoapodsProxyRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CocoapodsSpec.
func (in *CocoapodsSpec) DeepCopy() *CocoapodsSpec {
	if in == nil {
		return nil
	}
	out := new(CocoapodsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Component) DeepCopyInto(out *Component) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Component.
func (in *Component) DeepCopy() *Component {
	if in == nil {
		return nil
	}
	out := new(Component)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConanProxyRepository) DeepCopyInto(out *ConanProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConanProxyRepository.
func (in *ConanProxyRepository) DeepCopy() *ConanProxyRepository {
	if in == nil {
		return nil
	}
	out := new(ConanProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConanSpec) DeepCopyInto(out *ConanSpec) {
	*out = *in
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(ConanProxyRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConanSpec.
func (in *ConanSpec) DeepCopy() *ConanSpec {
	if in == nil {
		return nil
	}
	out := new(ConanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CondaProxyRepository) DeepCopyInto(out *CondaProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CondaProxyRepository.
func (in *CondaProxyRepository) DeepCopy() *CondaProxyRepository {
	if in == nil {
		return nil
	}
	out := new(CondaProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CondaSpec) DeepCopyInto(out *CondaSpec) {
	*out = *in
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(CondaProxyRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CondaSpec.
func (in *CondaSpec) DeepCopy() *CondaSpec {
	if in == nil {
		return nil
	}
	out := new(CondaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Criteria) DeepCopyInto(out *Criteria) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Criteria.
func (in *Criteria) DeepCopy() *Criteria {
	if in == nil {
		return nil
	}
	out := new(Criteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Docker) DeepCopyInto(out *Docker) {
	*out = *in
	if in.HTTPPort != nil {
		in, out := &in.HTTPPort, &out.HTTPPort
		*out = new(int)
		**out = **in
	}
	if in.HTTPSPort != nil {
		in, out := &in.HTTPSPort, &out.HTTPSPort
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Docker.
func (in *Docker) DeepCopy() *Docker {
	if in == nil {
		return nil
	}
	out := new(Docker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerGroupRepository) DeepCopyInto(out *DockerGroupRepository) {
	*out = *in
	out.Storage = in.Storage
	in.Group.DeepCopyInto(&out.Group)
	in.Docker.DeepCopyInto(&out.Docker)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerGroupRepository.
func (in *DockerGroupRepository) DeepCopy() *DockerGroupRepository {
	if in == nil {
		return nil
	}
	out := new(DockerGroupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerHostedRepository) DeepCopyInto(out *DockerHostedRepository) {
	*out = *in
	in.HostedSpec.DeepCopyInto(&out.HostedSpec)
	in.Docker.DeepCopyInto(&out.Docker)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerHostedRepository.
func (in *DockerHostedRepository) DeepCopy() *DockerHostedRepository {
	if in == nil {
		return nil
	}
	out := new(DockerHostedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerProxy) DeepCopyInto(out *DockerProxy) {
	*out = *in
	if in.IndexURL != nil {
		in, out := &in.IndexURL, &out.IndexURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerProxy.
func (in *DockerProxy) DeepCopy() *DockerProxy {
	if in == nil {
		return nil
	}
	out := new(DockerProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerProxyRepository) DeepCopyInto(out *DockerProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
	in.Docker.DeepCopyInto(&out.Docker)
	in.DockerProxy.DeepCopyInto(&out.DockerProxy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerProxyRepository.
func (in *DockerProxyRepository) DeepCopy() *DockerProxyRepository {
	if in == nil {
		return nil
	}
	out := new(DockerProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerSpec) DeepCopyInto(out *DockerSpec) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(DockerGroupRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(DockerProxyRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Hosted != nil {
		in, out := &in.Hosted, &out.Hosted
		*out = new(DockerHostedRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerSpec.
func (in *DockerSpec) DeepCopy() *DockerSpec {
	if in == nil {
		return nil
	}
	out := new(DockerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *File) DeepCopyInto(out *File) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new File.
func (in *File) DeepCopy() *File {
	if in == nil {
		return nil
	}
	out := new(File)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitLfsHostedRepository) DeepCopyInto(out *GitLfsHostedRepository) {
	*out = *in
	in.HostedSpec.DeepCopyInto(&out.HostedSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitLfsHostedRepository.
func (in *GitLfsHostedRepository) DeepCopy() *GitLfsHostedRepository {
	if in == nil {
		return nil
	}
	out := new(GitLfsHostedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitLfsSpec) DeepCopyInto(out *GitLfsSpec) {
	*out = *in
	if in.Hosted != nil {
		in, out := &in.Hosted, &out.Hosted
		*out = new(GitLfsHostedRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitLfsSpec.
func (in *GitLfsSpec) DeepCopy() *GitLfsSpec {
	if in == nil {
		return nil
	}
	out := new(GitLfsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoGroupRepository) DeepCopyInto(out *GoGroupRepository) {
	*out = *in
	in.GroupSpec.DeepCopyInto(&out.GroupSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoGroupRepository.
func (in *GoGroupRepository) DeepCopy() *GoGroupRepository {
	if in == nil {
		return nil
	}
	out := new(GoGroupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoProxyRepository) DeepCopyInto(out *GoProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoProxyRepository.
func (in *GoProxyRepository) DeepCopy() *GoProxyRepository {
	if in == nil {
		return nil
	}
	out := new(GoProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoSpec) DeepCopyInto(out *GoSpec) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(GoGroupRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(GoProxyRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoSpec.
func (in *GoSpec) DeepCopy() *GoSpec {
	if in == nil {
		return nil
	}
	out := new(GoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Group) DeepCopyInto(out *Group) {
	*out = *in
	if in.MemberNames != nil {
		in, out := &in.MemberNames, &out.MemberNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Group.
func (in *Group) DeepCopy() *Group {
	if in == nil {
		return nil
	}
	out := new(Group)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupDeploy) DeepCopyInto(out *GroupDeploy) {
	*out = *in
	if in.MemberNames != nil {
		in, out := &in.MemberNames, &out.MemberNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WritableMember != nil {
		in, out := &in.WritableMember, &out.WritableMember
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupDeploy.
func (in *GroupDeploy) DeepCopy() *GroupDeploy {
	if in == nil {
		return nil
	}
	out := new(GroupDeploy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSpec) DeepCopyInto(out *GroupSpec) {
	*out = *in
	in.Group.DeepCopyInto(&out.Group)
	out.Storage = in.Storage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSpec.
func (in *GroupSpec) DeepCopy() *GroupSpec {
	if in == nil {
		return nil
	}
	out := new(GroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPClient) DeepCopyInto(out *HTTPClient) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(HTTPClientAuthentication)
		**out = **in
	}
	if in.Connection != nil {
		in, out := &in.Connection, &out.Connection
		*out = new(HTTPClientConnection)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPClient.
func (in *HTTPClient) DeepCopy() *HTTPClient {
	if in == nil {
		return nil
	}
	out := new(HTTPClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPClientAuthentication) DeepCopyInto(out *HTTPClientAuthentication) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPClientAuthentication.
func (in *HTTPClientAuthentication) DeepCopy() *HTTPClientAuthentication {
	if in == nil {
		return nil
	}
	out := new(HTTPClientAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPClientAuthenticationWithPreemptive) DeepCopyInto(out *HTTPClientAuthenticationWithPreemptive) {
	*out = *in
	if in.Preemptive != nil {
		in, out := &in.Preemptive, &out.Preemptive
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPClientAuthenticationWithPreemptive.
func (in *HTTPClientAuthenticationWithPreemptive) DeepCopy() *HTTPClientAuthenticationWithPreemptive {
	if in == nil {
		return nil
	}
	out := new(HTTPClientAuthenticationWithPreemptive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPClientConnection) DeepCopyInto(out *HTTPClientConnection) {
	*out = *in
	if in.EnableCircularRedirects != nil {
		in, out := &in.EnableCircularRedirects, &out.EnableCircularRedirects
		*out = new(bool)
		**out = **in
	}
	if in.EnableCookies != nil {
		in, out := &in.EnableCookies, &out.EnableCookies
		*out = new(bool)
		**out = **in
	}
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(int)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int)
		**out = **in
	}
	if in.UseTrustStore != nil {
		in, out := &in.UseTrustStore, &out.UseTrustStore
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPClientConnection.
func (in *HTTPClientConnection) DeepCopy() *HTTPClientConnection {
	if in == nil {
		return nil
	}
	out := new(HTTPClientConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPClientWithPreemptiveAuth) DeepCopyInto(out *HTTPClientWithPreemptiveAuth) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(HTTPClientAuthenticationWithPreemptive)
		(*in).DeepCopyInto(*out)
	}
	if in.Connection != nil {
		in, out := &in.Connection, &out.Connection
		*out = new(HTTPClientConnection)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPClientWithPreemptiveAuth.
func (in *HTTPClientWithPreemptiveAuth) DeepCopy() *HTTPClientWithPreemptiveAuth {
	if in == nil {
		return nil
	}
	out := new(HTTPClientWithPreemptiveAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmHostedRepository) DeepCopyInto(out *HelmHostedRepository) {
	*out = *in
	in.HostedSpec.DeepCopyInto(&out.HostedSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmHostedRepository.
func (in *HelmHostedRepository) DeepCopy() *HelmHostedRepository {
	if in == nil {
		return nil
	}
	out := new(HelmHostedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmProxyRepository) DeepCopyInto(out *HelmProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmProxyRepository.
func (in *HelmProxyRepository) DeepCopy() *HelmProxyRepository {
	if in == nil {
		return nil
	}
	out := new(HelmProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmSpec) DeepCopyInto(out *HelmSpec) {
	*out = *in
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(HelmProxyRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Hosted != nil {
		in, out := &in.Hosted, &out.Hosted
		*out = new(HelmHostedRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmSpec.
func (in *HelmSpec) DeepCopy() *HelmSpec {
	if in == nil {
		return nil
	}
	out := new(HelmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedSpec) DeepCopyInto(out *HostedSpec) {
	*out = *in
	out.Storage = in.Storage
	if in.Cleanup != nil {
		in, out := &in.Cleanup, &out.Cleanup
		*out = new(Cleanup)
		(*in).DeepCopyInto(*out)
	}
	if in.Component != nil {
		in, out := &in.Component, &out.Component
		*out = new(Component)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedSpec.
func (in *HostedSpec) DeepCopy() *HostedSpec {
	if in == nil {
		return nil
	}
	out := new(HostedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedStorage) DeepCopyInto(out *HostedStorage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedStorage.
func (in *HostedStorage) DeepCopy() *HostedStorage {
	if in == nil {
		return nil
	}
	out := new(HostedStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Maven) DeepCopyInto(out *Maven) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Maven.
func (in *Maven) DeepCopy() *Maven {
	if in == nil {
		return nil
	}
	out := new(Maven)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MavenGroupRepository) DeepCopyInto(out *MavenGroupRepository) {
	*out = *in
	out.Maven = in.Maven
	in.GroupSpec.DeepCopyInto(&out.GroupSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MavenGroupRepository.
func (in *MavenGroupRepository) DeepCopy() *MavenGroupRepository {
	if in == nil {
		return nil
	}
	out := new(MavenGroupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MavenHostedRepository) DeepCopyInto(out *MavenHostedRepository) {
	*out = *in
	out.Maven = in.Maven
	in.HostedSpec.DeepCopyInto(&out.HostedSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MavenHostedRepository.
func (in *MavenHostedRepository) DeepCopy() *MavenHostedRepository {
	if in == nil {
		return nil
	}
	out := new(MavenHostedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MavenProxyRepository) DeepCopyInto(out *MavenProxyRepository) {
	*out = *in
	out.Storage = in.Storage
	out.Proxy = in.Proxy
	out.NegativeCache = in.NegativeCache
	in.HTTPClient.DeepCopyInto(&out.HTTPClient)
	if in.RoutingRule != nil {
		in, out := &in.RoutingRule, &out.RoutingRule
		*out = new(string)
		**out = **in
	}
	if in.Cleanup != nil {
		in, out := &in.Cleanup, &out.Cleanup
		*out = new(Cleanup)
		(*in).DeepCopyInto(*out)
	}
	out.Maven = in.Maven
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MavenProxyRepository.
func (in *MavenProxyRepository) DeepCopy() *MavenProxyRepository {
	if in == nil {
		return nil
	}
	out := new(MavenProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MavenSpec) DeepCopyInto(out *MavenSpec) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(MavenGroupRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(MavenProxyRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Hosted != nil {
		in, out := &in.Hosted, &out.Hosted
		*out = new(MavenHostedRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MavenSpec.
func (in *MavenSpec) DeepCopy() *MavenSpec {
	if in == nil {
		return nil
	}
	out := new(MavenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NegativeCache) DeepCopyInto(out *NegativeCache) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NegativeCache.
func (in *NegativeCache) DeepCopy() *NegativeCache {
	if in == nil {
		return nil
	}
	out := new(NegativeCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nexus) DeepCopyInto(out *Nexus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nexus.
func (in *Nexus) DeepCopy() *Nexus {
	if in == nil {
		return nil
	}
	out := new(Nexus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Nexus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusBlobStore) DeepCopyInto(out *NexusBlobStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusBlobStore.
func (in *NexusBlobStore) DeepCopy() *NexusBlobStore {
	if in == nil {
		return nil
	}
	out := new(NexusBlobStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusBlobStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusBlobStoreList) DeepCopyInto(out *NexusBlobStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NexusBlobStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusBlobStoreList.
func (in *NexusBlobStoreList) DeepCopy() *NexusBlobStoreList {
	if in == nil {
		return nil
	}
	out := new(NexusBlobStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusBlobStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusBlobStoreSpec) DeepCopyInto(out *NexusBlobStoreSpec) {
	*out = *in
	if in.SoftQuota != nil {
		in, out := &in.SoftQuota, &out.SoftQuota
		*out = new(SoftQuota)
		**out = **in
	}
	out.File = in.File
	out.NexusRef = in.NexusRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusBlobStoreSpec.
func (in *NexusBlobStoreSpec) DeepCopy() *NexusBlobStoreSpec {
	if in == nil {
		return nil
	}
	out := new(NexusBlobStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusBlobStoreStatus) DeepCopyInto(out *NexusBlobStoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusBlobStoreStatus.
func (in *NexusBlobStoreStatus) DeepCopy() *NexusBlobStoreStatus {
	if in == nil {
		return nil
	}
	out := new(NexusBlobStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusCleanupPolicy) DeepCopyInto(out *NexusCleanupPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusCleanupPolicy.
func (in *NexusCleanupPolicy) DeepCopy() *NexusCleanupPolicy {
	if in == nil {
		return nil
	}
	out := new(NexusCleanupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusCleanupPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusCleanupPolicyList) DeepCopyInto(out *NexusCleanupPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NexusCleanupPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusCleanupPolicyList.
func (in *NexusCleanupPolicyList) DeepCopy() *NexusCleanupPolicyList {
	if in == nil {
		return nil
	}
	out := new(NexusCleanupPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusCleanupPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusCleanupPolicySpec) DeepCopyInto(out *NexusCleanupPolicySpec) {
	*out = *in
	out.Criteria = in.Criteria
	out.NexusRef = in.NexusRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusCleanupPolicySpec.
func (in *NexusCleanupPolicySpec) DeepCopy() *NexusCleanupPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NexusCleanupPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusCleanupPolicyStatus) DeepCopyInto(out *NexusCleanupPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusCleanupPolicyStatus.
func (in *NexusCleanupPolicyStatus) DeepCopy() *NexusCleanupPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NexusCleanupPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusList) DeepCopyInto(out *NexusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Nexus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusList.
func (in *NexusList) DeepCopy() *NexusList {
	if in == nil {
		return nil
	}
	out := new(NexusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusRepository) DeepCopyInto(out *NexusRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusRepository.
func (in *NexusRepository) DeepCopy() *NexusRepository {
	if in == nil {
		return nil
	}
	out := new(NexusRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusRepositoryList) DeepCopyInto(out *NexusRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NexusRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusRepositoryList.
func (in *NexusRepositoryList) DeepCopy() *NexusRepositoryList {
	if in == nil {
		return nil
	}
	out := new(NexusRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusRepositorySpec) DeepCopyInto(out *NexusRepositorySpec) {
	*out = *in
	if in.Apt != nil {
		in, out := &in.Apt, &out.Apt
		*out = new(AptSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Bower != nil {
		in, out := &in.Bower, &out.Bower
		*out = new(BowerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Cocoapods != nil {
		in, out := &in.Cocoapods, &out.Cocoapods
		*out = new(CocoapodsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Conan != nil {
		in, out := &in.Conan, &out.Conan
		*out = new(ConanSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Conda != nil {
		in, out := &in.Conda, &out.Conda
		*out = new(CondaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = new(DockerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GitLfs != nil {
		in, out := &in.GitLfs, &out.GitLfs
		*out = new(GitLfsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Go != nil {
		in, out := &in.Go, &out.Go
		*out = new(GoSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(HelmSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Maven != nil {
		in, out := &in.Maven, &out.Maven
		*out = new(MavenSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Npm != nil {
		in, out := &in.Npm, &out.Npm
		*out = new(NpmSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Nuget != nil {
		in, out := &in.Nuget, &out.Nuget
		*out = new(NugetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.P2 != nil {
		in, out := &in.P2, &out.P2
		*out = new(P2Spec)
		(*in).DeepCopyInto(*out)
	}
	if in.Pypi != nil {
		in, out := &in.Pypi, &out.Pypi
		*out = new(PypiSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.R != nil {
		in, out := &in.R, &out.R
		*out = new(RSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = new(RawSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RubyGems != nil {
		in, out := &in.RubyGems, &out.RubyGems
		*out = new(RubyGemsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Yum != nil {
		in, out := &in.Yum, &out.Yum
		*out = new(YumSpec)
		(*in).DeepCopyInto(*out)
	}
	out.NexusRef = in.NexusRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusRepositorySpec.
func (in *NexusRepositorySpec) DeepCopy() *NexusRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(NexusRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusRepositoryStatus) DeepCopyInto(out *NexusRepositoryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusRepositoryStatus.
func (in *NexusRepositoryStatus) DeepCopy() *NexusRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(NexusRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusRole) DeepCopyInto(out *NexusRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusRole.
func (in *NexusRole) DeepCopy() *NexusRole {
	if in == nil {
		return nil
	}
	out := new(NexusRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusRoleList) DeepCopyInto(out *NexusRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NexusRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusRoleList.
func (in *NexusRoleList) DeepCopy() *NexusRoleList {
	if in == nil {
		return nil
	}
	out := new(NexusRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusRoleSpec) DeepCopyInto(out *NexusRoleSpec) {
	*out = *in
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.NexusRef = in.NexusRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusRoleSpec.
func (in *NexusRoleSpec) DeepCopy() *NexusRoleSpec {
	if in == nil {
		return nil
	}
	out := new(NexusRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusRoleStatus) DeepCopyInto(out *NexusRoleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusRoleStatus.
func (in *NexusRoleStatus) DeepCopy() *NexusRoleStatus {
	if in == nil {
		return nil
	}
	out := new(NexusRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusScript) DeepCopyInto(out *NexusScript) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusScript.
func (in *NexusScript) DeepCopy() *NexusScript {
	if in == nil {
		return nil
	}
	out := new(NexusScript)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusScript) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusScriptList) DeepCopyInto(out *NexusScriptList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NexusScript, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusScriptList.
func (in *NexusScriptList) DeepCopy() *NexusScriptList {
	if in == nil {
		return nil
	}
	out := new(NexusScriptList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusScriptList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusScriptSpec) DeepCopyInto(out *NexusScriptSpec) {
	*out = *in
	out.NexusRef = in.NexusRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusScriptSpec.
func (in *NexusScriptSpec) DeepCopy() *NexusScriptSpec {
	if in == nil {
		return nil
	}
	out := new(NexusScriptSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusScriptStatus) DeepCopyInto(out *NexusScriptStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusScriptStatus.
func (in *NexusScriptStatus) DeepCopy() *NexusScriptStatus {
	if in == nil {
		return nil
	}
	out := new(NexusScriptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusSpec) DeepCopyInto(out *NexusSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusSpec.
func (in *NexusSpec) DeepCopy() *NexusSpec {
	if in == nil {
		return nil
	}
	out := new(NexusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusStatus) DeepCopyInto(out *NexusStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusStatus.
func (in *NexusStatus) DeepCopy() *NexusStatus {
	if in == nil {
		return nil
	}
	out := new(NexusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusUser) DeepCopyInto(out *NexusUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusUser.
func (in *NexusUser) DeepCopy() *NexusUser {
	if in == nil {
		return nil
	}
	out := new(NexusUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusUserList) DeepCopyInto(out *NexusUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NexusUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusUserList.
func (in *NexusUserList) DeepCopy() *NexusUserList {
	if in == nil {
		return nil
	}
	out := new(NexusUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusUserSpec) DeepCopyInto(out *NexusUserSpec) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.NexusRef = in.NexusRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusUserSpec.
func (in *NexusUserSpec) DeepCopy() *NexusUserSpec {
	if in == nil {
		return nil
	}
	out := new(NexusUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusUserStatus) DeepCopyInto(out *NexusUserStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusUserStatus.
func (in *NexusUserStatus) DeepCopy() *NexusUserStatus {
	if in == nil {
		return nil
	}
	out := new(NexusUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Npm) DeepCopyInto(out *Npm) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Npm.
func (in *Npm) DeepCopy() *Npm {
	if in == nil {
		return nil
	}
	out := new(Npm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NpmGroupRepository) DeepCopyInto(out *NpmGroupRepository) {
	*out = *in
	in.GroupSpec.DeepCopyInto(&out.GroupSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NpmGroupRepository.
func (in *NpmGroupRepository) DeepCopy() *NpmGroupRepository {
	if in == nil {
		return nil
	}
	out := new(NpmGroupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NpmHostedRepository) DeepCopyInto(out *NpmHostedRepository) {
	*out = *in
	in.HostedSpec.DeepCopyInto(&out.HostedSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NpmHostedRepository.
func (in *NpmHostedRepository) DeepCopy() *NpmHostedRepository {
	if in == nil {
		return nil
	}
	out := new(NpmHostedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NpmProxyRepository) DeepCopyInto(out *NpmProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
	if in.Npm != nil {
		in, out := &in.Npm, &out.Npm
		*out = new(Npm)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NpmProxyRepository.
func (in *NpmProxyRepository) DeepCopy() *NpmProxyRepository {
	if in == nil {
		return nil
	}
	out := new(NpmProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NpmSpec) DeepCopyInto(out *NpmSpec) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(NpmGroupRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(NpmProxyRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Hosted != nil {
		in, out := &in.Hosted, &out.Hosted
		*out = new(NpmHostedRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NpmSpec.
func (in *NpmSpec) DeepCopy() *NpmSpec {
	if in == nil {
		return nil
	}
	out := new(NpmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NugetGroupRepository) DeepCopyInto(out *NugetGroupRepository) {
	*out = *in
	in.GroupSpec.DeepCopyInto(&out.GroupSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NugetGroupRepository.
func (in *NugetGroupRepository) DeepCopy() *NugetGroupRepository {
	if in == nil {
		return nil
	}
	out := new(NugetGroupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NugetHostedRepository) DeepCopyInto(out *NugetHostedRepository) {
	*out = *in
	in.HostedSpec.DeepCopyInto(&out.HostedSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NugetHostedRepository.
func (in *NugetHostedRepository) DeepCopy() *NugetHostedRepository {
	if in == nil {
		return nil
	}
	out := new(NugetHostedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NugetProxy) DeepCopyInto(out *NugetProxy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NugetProxy.
func (in *NugetProxy) DeepCopy() *NugetProxy {
	if in == nil {
		return nil
	}
	out := new(NugetProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NugetProxyRepository) DeepCopyInto(out *NugetProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
	out.NugetProxy = in.NugetProxy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NugetProxyRepository.
func (in *NugetProxyRepository) DeepCopy() *NugetProxyRepository {
	if in == nil {
		return nil
	}
	out := new(NugetProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NugetSpec) DeepCopyInto(out *NugetSpec) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(NugetGroupRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(NugetProxyRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Hosted != nil {
		in, out := &in.Hosted, &out.Hosted
		*out = new(NugetHostedRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NugetSpec.
func (in *NugetSpec) DeepCopy() *NugetSpec {
	if in == nil {
		return nil
	}
	out := new(NugetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2ProxyRepository) DeepCopyInto(out *P2ProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2ProxyRepository.
func (in *P2ProxyRepository) DeepCopy() *P2ProxyRepository {
	if in == nil {
		return nil
	}
	out := new(P2ProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2Spec) DeepCopyInto(out *P2Spec) {
	*out = *in
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(P2ProxyRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2Spec.
func (in *P2Spec) DeepCopy() *P2Spec {
	if in == nil {
		return nil
	}
	out := new(P2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Proxy) DeepCopyInto(out *Proxy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Proxy.
func (in *Proxy) DeepCopy() *Proxy {
	if in == nil {
		return nil
	}
	out := new(Proxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxySpec) DeepCopyInto(out *ProxySpec) {
	*out = *in
	out.Storage = in.Storage
	out.Proxy = in.Proxy
	out.NegativeCache = in.NegativeCache
	in.HTTPClient.DeepCopyInto(&out.HTTPClient)
	if in.RoutingRule != nil {
		in, out := &in.RoutingRule, &out.RoutingRule
		*out = new(string)
		**out = **in
	}
	if in.Cleanup != nil {
		in, out := &in.Cleanup, &out.Cleanup
		*out = new(Cleanup)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxySpec.
func (in *ProxySpec) DeepCopy() *ProxySpec {
	if in == nil {
		return nil
	}
	out := new(ProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PypiGroupRepository) DeepCopyInto(out *PypiGroupRepository) {
	*out = *in
	in.GroupSpec.DeepCopyInto(&out.GroupSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PypiGroupRepository.
func (in *PypiGroupRepository) DeepCopy() *PypiGroupRepository {
	if in == nil {
		return nil
	}
	out := new(PypiGroupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PypiHostedRepository) DeepCopyInto(out *PypiHostedRepository) {
	*out = *in
	in.HostedSpec.DeepCopyInto(&out.HostedSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PypiHostedRepository.
func (in *PypiHostedRepository) DeepCopy() *PypiHostedRepository {
	if in == nil {
		return nil
	}
	out := new(PypiHostedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PypiProxyRepository) DeepCopyInto(out *PypiProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PypiProxyRepository.
func (in *PypiProxyRepository) DeepCopy() *PypiProxyRepository {
	if in == nil {
		return nil
	}
	out := new(PypiProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PypiSpec) DeepCopyInto(out *PypiSpec) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(PypiGroupRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(PypiProxyRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Hosted != nil {
		in, out := &in.Hosted, &out.Hosted
		*out = new(PypiHostedRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PypiSpec.
func (in *PypiSpec) DeepCopy() *PypiSpec {
	if in == nil {
		return nil
	}
	out := new(PypiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RGroupRepository) DeepCopyInto(out *RGroupRepository) {
	*out = *in
	in.GroupSpec.DeepCopyInto(&out.GroupSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RGroupRepository.
func (in *RGroupRepository) DeepCopy() *RGroupRepository {
	if in == nil {
		return nil
	}
	out := new(RGroupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHostedRepository) DeepCopyInto(out *RHostedRepository) {
	*out = *in
	in.HostedSpec.DeepCopyInto(&out.HostedSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHostedRepository.
func (in *RHostedRepository) DeepCopy() *RHostedRepository {
	if in == nil {
		return nil
	}
	out := new(RHostedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RProxyRepository) DeepCopyInto(out *RProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RProxyRepository.
func (in *RProxyRepository) DeepCopy() *RProxyRepository {
	if in == nil {
		return nil
	}
	out := new(RProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RSpec) DeepCopyInto(out *RSpec) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(RGroupRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(RProxyRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Hosted != nil {
		in, out := &in.Hosted, &out.Hosted
		*out = new(RHostedRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RSpec.
func (in *RSpec) DeepCopy() *RSpec {
	if in == nil {
		return nil
	}
	out := new(RSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Raw) DeepCopyInto(out *Raw) {
	*out = *in
	if in.ContentDisposition != nil {
		in, out := &in.ContentDisposition, &out.ContentDisposition
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Raw.
func (in *Raw) DeepCopy() *Raw {
	if in == nil {
		return nil
	}
	out := new(Raw)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawGroupRepository) DeepCopyInto(out *RawGroupRepository) {
	*out = *in
	in.GroupSpec.DeepCopyInto(&out.GroupSpec)
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = new(Raw)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawGroupRepository.
func (in *RawGroupRepository) DeepCopy() *RawGroupRepository {
	if in == nil {
		return nil
	}
	out := new(RawGroupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawHostedRepository) DeepCopyInto(out *RawHostedRepository) {
	*out = *in
	in.HostedSpec.DeepCopyInto(&out.HostedSpec)
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = new(Raw)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawHostedRepository.
func (in *RawHostedRepository) DeepCopy() *RawHostedRepository {
	if in == nil {
		return nil
	}
	out := new(RawHostedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawProxyRepository) DeepCopyInto(out *RawProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = new(Raw)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawProxyRepository.
func (in *RawProxyRepository) DeepCopy() *RawProxyRepository {
	if in == nil {
		return nil
	}
	out := new(RawProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawSpec) DeepCopyInto(out *RawSpec) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(RawGroupRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(RawProxyRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Hosted != nil {
		in, out := &in.Hosted, &out.Hosted
		*out = new(RawHostedRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawSpec.
func (in *RawSpec) DeepCopy() *RawSpec {
	if in == nil {
		return nil
	}
	out := new(RawSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RubyGemsGroupRepository) DeepCopyInto(out *RubyGemsGroupRepository) {
	*out = *in
	in.GroupSpec.DeepCopyInto(&out.GroupSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RubyGemsGroupRepository.
func (in *RubyGemsGroupRepository) DeepCopy() *RubyGemsGroupRepository {
	if in == nil {
		return nil
	}
	out := new(RubyGemsGroupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RubyGemsHostedRepository) DeepCopyInto(out *RubyGemsHostedRepository) {
	*out = *in
	in.HostedSpec.DeepCopyInto(&out.HostedSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RubyGemsHostedRepository.
func (in *RubyGemsHostedRepository) DeepCopy() *RubyGemsHostedRepository {
	if in == nil {
		return nil
	}
	out := new(RubyGemsHostedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RubyGemsProxyRepository) DeepCopyInto(out *RubyGemsProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RubyGemsProxyRepository.
func (in *RubyGemsProxyRepository) DeepCopy() *RubyGemsProxyRepository {
	if in == nil {
		return nil
	}
	out := new(RubyGemsProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RubyGemsSpec) DeepCopyInto(out *RubyGemsSpec) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(RubyGemsGroupRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(RubyGemsProxyRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Hosted != nil {
		in, out := &in.Hosted, &out.Hosted
		*out = new(RubyGemsHostedRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RubyGemsSpec.
func (in *RubyGemsSpec) DeepCopy() *RubyGemsSpec {
	if in == nil {
		return nil
	}
	out := new(RubyGemsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SoftQuota) DeepCopyInto(out *SoftQuota) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SoftQuota.
func (in *SoftQuota) DeepCopy() *SoftQuota {
	if in == nil {
		return nil
	}
	out := new(SoftQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Storage) DeepCopyInto(out *Storage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Storage.
func (in *Storage) DeepCopy() *Storage {
	if in == nil {
		return nil
	}
	out := new(Storage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Yum) DeepCopyInto(out *Yum) {
	*out = *in
	if in.DeployPolicy != nil {
		in, out := &in.DeployPolicy, &out.DeployPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Yum.
func (in *Yum) DeepCopy() *Yum {
	if in == nil {
		return nil
	}
	out := new(Yum)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YumGroupRepository) DeepCopyInto(out *YumGroupRepository) {
	*out = *in
	in.GroupSpec.DeepCopyInto(&out.GroupSpec)
	if in.YumSigning != nil {
		in, out := &in.YumSigning, &out.YumSigning
		*out = new(YumSigning)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YumGroupRepository.
func (in *YumGroupRepository) DeepCopy() *YumGroupRepository {
	if in == nil {
		return nil
	}
	out := new(YumGroupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YumHostedRepository) DeepCopyInto(out *YumHostedRepository) {
	*out = *in
	in.HostedSpec.DeepCopyInto(&out.HostedSpec)
	in.Yum.DeepCopyInto(&out.Yum)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YumHostedRepository.
func (in *YumHostedRepository) DeepCopy() *YumHostedRepository {
	if in == nil {
		return nil
	}
	out := new(YumHostedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YumProxyRepository) DeepCopyInto(out *YumProxyRepository) {
	*out = *in
	in.ProxySpec.DeepCopyInto(&out.ProxySpec)
	if in.YumSigning != nil {
		in, out := &in.YumSigning, &out.YumSigning
		*out = new(YumSigning)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YumProxyRepository.
func (in *YumProxyRepository) DeepCopy() *YumProxyRepository {
	if in == nil {
		return nil
	}
	out := new(YumProxyRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YumSigning) DeepCopyInto(out *YumSigning) {
	*out = *in
	if in.Keypair != nil {
		in, out := &in.Keypair, &out.Keypair
		*out = new(string)
		**out = **in
	}
	if in.Passphrase != nil {
		in, out := &in.Passphrase, &out.Passphrase
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YumSigning.
func (in *YumSigning) DeepCopy() *YumSigning {
	if in == nil {
		return nil
	}
	out := new(YumSigning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YumSpec) DeepCopyInto(out *YumSpec) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(YumGroupRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(YumProxyRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Hosted != nil {
		in, out := &in.Hosted, &out.Hosted
		*out = new(YumHostedRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YumSpec.
func (in *YumSpec) DeepCopy() *YumSpec {
	if in == nil {
		return nil
	}
	out := new(YumSpec)
	in.DeepCopyInto(out)
	return out
}
