apiVersion: v2
description: A Helm chart for KubeRocketCI Nexus Operator
home: https://docs.kuberocketci.io/
name: nexus-operator
type: application
version: 3.5.0-SNAPSHOT
appVersion: 3.5.0-SNAPSHOT
icon: https://docs.kuberocketci.io/img/logo.svg
keywords:
  - edp
  - nexus
  - operator
  - artifact
  - storage
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/kuberocketci
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-nexus-operator
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: nexus-operator:3.4.0
      image: epamedp/nexus-operator:3.4.0
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/crds: |
    - kind: Nexus
      version: edp.epam.com/v1alpha1
      name: nexus
      displayName: Nexus
      description: Nexus server configuration
    - kind: NexusUser
      version: edp.epam.com/v1alpha1
      name: nexususer
      displayName: NexusUser
      description: Nexus user management
    - kind: NexusRole
      version: edp.epam.com/v1alpha1
      name: nexusrole
      displayName: NexusRole
      description: Nexus role management
  artifacthub.io/crdsExamples: |
    - apiVersion: edp.epam.com/v1alpha1
      kind: Nexus
      metadata:
        name: nexus-sample
      spec:
        url: https://nexus-example.com
        secret: nexus-secret
    - apiVersion: edp.epam.com/v1alpha1
      kind: NexusRole
      metadata:
        name: nexusrole-sample
      spec:
        id: test-role
        nexusRef:
          name: nexus-sample
          kind: Nexus
        name: test-role
        description: test-role
        privileges:
          - nx-blobstores-all
    - apiVersion: edp.epam.com/v1alpha1
      kind: NexusUser
      metadata:
        name: user-sample
      spec:
        id: test-user
        firstName: John1
        lastName: Doe
        email: test@gmail.com
        secret: $user-secret:password
        roles:
          - nx-admin
        nexusRef:
          name: nexus-sample
          kind: Nexus
  artifacthub.io/links: |
    - name: KubeRocketCI Documentation
      url: https://docs.kuberocketci.io
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/kuberocketci
