apiVersion: v2
description: A Helm chart for EDP Nexus Operator
home: https://solutionshub.epam.com/solution/epam-delivery-platform
name: nexus-operator
type: application
version: v2.8.0
appVersion: v2.8.0
maintainers:
    - name: EPAM EDP Team
sources:
    - https://github.com/epam/edp-nexus-operator
