apiVersion: v2
description: A Helm chart for EDP Nexus Operator
home: https://epam.github.io/edp-install/
name: nexus-operator
type: application
version: 2.11.0
appVersion: 2.11.0
icon: https://epam.github.io/edp-install/assets/logo.png
keywords:
  - edp
  - nexus
  - operator
  - artifact
  - storage
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/epam-delivery-platform
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-nexus-operator
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: nexus-operator:2.11.0
      image: epamedp/nexus-operator:2.11.0
    - name: nexus3:3.38.1
      image: sonatype/nexus3:3.38.1
    - name: alpine:3.15.4
      image: alpine:3.15.4
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/crds: |
    - kind: Nexus
      version: v2.edp.epam.com/v1alpha1
      name: nexus
      displayName: Nexus
      description: Nexus server configuration
    - kind: NexusUser
      version: v2.edp.epam.com/v1alpha1
      name: nexususer
      displayName: NexusUser
      description: Nexus user management
  artifacthub.io/crdsExamples: |
    - apiVersion: v2.edp.epam.com/v1alpha1
      kind: Nexus
      metadata:
        name: nexus
      spec:
        basePath: 'blank'
        edpSpec:
          dnsWildcard: localhost.com
        image: sonatype/nexus3
        keycloakSpec:
          enabled: true
          proxyImage: quay.io/keycloak/keycloak-gatekeeper:10.0.0
          roles:
            - developer
            - administrator
        users:
          - roles:
              - nx-admin
            username: nx@example.com
        version: 3.38.1
        volumes:
          - capacity: 30Gi
            name: data
            storage_class: gp2
    - apiVersion: v2.edp.epam.com/v1
      kind: NexusUser
      metadata:
        name: test
      spec:
        ownerName: nexus
        firstName: John
        lastName: Doe
        email: john.doe@example.com
        userId: jondoe14
        roles: ["edp-admin"]
        status: "active"
  artifacthub.io/links: |
    - name: EDP Documentation
      url: https://epam.github.io/edp-install/
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/epam-delivery-platform
