apiVersion: v2
description: A Helm chart for EDP Nexus Operator
home: https://solutionshub.epam.com/solution/epam-delivery-platform
name: nexus-operator
type: application
version: 2.8.1
appVersion: 2.8.1
maintainers:
    - name: EPAM EDP Team
sources:
    - https://github.com/epam/edp-nexus-operator
