# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/edp.epam.com_nexuses.yaml
- bases/edp.epam.com_nexusroles.yaml
- bases/edp.epam.com_nexususers.yaml
- bases/edp.epam.com_nexusrepositories.yaml
- bases/edp.epam.com_nexusscripts.yaml
- bases/edp.epam.com_nexusblobstores.yaml
- bases/edp.epam.com_nexuscleanuppolicies.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_nexuses.yaml
#- path: patches/webhook_in_nexusroles.yaml
#- path: patches/webhook_in_nexususers.yaml
#- path: patches/webhook_in_nexusrepositories.yaml
#- path: patches/webhook_in_nexusscripts.yaml
#- path: patches/webhook_in_nexusblobstores.yaml
#- path: patches/webhook_in_nexuscleanuppolicies.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_nexuses.yaml
#- patches/cainjection_in_nexususers.yaml
#- patches/cainjection_in_nexusroles.yaml
#- patches/cainjection_in_nexusrepositories.yaml
#- patches/cainjection_in_nexusscripts.yaml
#- patches/cainjection_in_nexusblobstores.yaml
#- patches/cainjection_in_nexuscleanuppolicies.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
