{{ if eq .Values.global.platform "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nexus
  name: nexus
spec:
  host: {{if .Values.nexus.basePath}}{{ .Values.global.dnsWildCard }}{{else}}nexus-{{ .Values.global.edpName }}.{{ .Values.global.dnsWildCard }}{{end}}
  path: {{if .Values.nexus.basePath}}/{{.Values.nexus.basePath}}(/|$)(.*){{else}}/{{end}}
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nexus
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
{{ end }}