// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/datadrivers/go-nexus-client/nexus3/schema/blobstore"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileBlobStore creates a new instance of MockFileBlobStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileBlobStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileBlobStore {
	mock := &MockFileBlobStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileBlobStore is an autogenerated mock type for the FileBlobStore type
type MockFileBlobStore struct {
	mock.Mock
}

type MockFileBlobStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileBlobStore) EXPECT() *MockFileBlobStore_Expecter {
	return &MockFileBlobStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockFileBlobStore
func (_mock *MockFileBlobStore) Create(bs *blobstore.File) error {
	ret := _mock.Called(bs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*blobstore.File) error); ok {
		r0 = returnFunc(bs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileBlobStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFileBlobStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - bs *blobstore.File
func (_e *MockFileBlobStore_Expecter) Create(bs interface{}) *MockFileBlobStore_Create_Call {
	return &MockFileBlobStore_Create_Call{Call: _e.mock.On("Create", bs)}
}

func (_c *MockFileBlobStore_Create_Call) Run(run func(bs *blobstore.File)) *MockFileBlobStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *blobstore.File
		if args[0] != nil {
			arg0 = args[0].(*blobstore.File)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileBlobStore_Create_Call) Return(err error) *MockFileBlobStore_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileBlobStore_Create_Call) RunAndReturn(run func(bs *blobstore.File) error) *MockFileBlobStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockFileBlobStore
func (_mock *MockFileBlobStore) Delete(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileBlobStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFileBlobStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - name string
func (_e *MockFileBlobStore_Expecter) Delete(name interface{}) *MockFileBlobStore_Delete_Call {
	return &MockFileBlobStore_Delete_Call{Call: _e.mock.On("Delete", name)}
}

func (_c *MockFileBlobStore_Delete_Call) Run(run func(name string)) *MockFileBlobStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileBlobStore_Delete_Call) Return(err error) *MockFileBlobStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileBlobStore_Delete_Call) RunAndReturn(run func(name string) error) *MockFileBlobStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockFileBlobStore
func (_mock *MockFileBlobStore) Get(name string) (*blobstore.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *blobstore.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*blobstore.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *blobstore.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blobstore.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileBlobStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockFileBlobStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
func (_e *MockFileBlobStore_Expecter) Get(name interface{}) *MockFileBlobStore_Get_Call {
	return &MockFileBlobStore_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *MockFileBlobStore_Get_Call) Run(run func(name string)) *MockFileBlobStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileBlobStore_Get_Call) Return(file *blobstore.File, err error) *MockFileBlobStore_Get_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileBlobStore_Get_Call) RunAndReturn(run func(name string) (*blobstore.File, error)) *MockFileBlobStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockFileBlobStore
func (_mock *MockFileBlobStore) Update(name string, bs *blobstore.File) error {
	ret := _mock.Called(name, bs)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *blobstore.File) error); ok {
		r0 = returnFunc(name, bs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileBlobStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFileBlobStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - name string
//   - bs *blobstore.File
func (_e *MockFileBlobStore_Expecter) Update(name interface{}, bs interface{}) *MockFileBlobStore_Update_Call {
	return &MockFileBlobStore_Update_Call{Call: _e.mock.On("Update", name, bs)}
}

func (_c *MockFileBlobStore_Update_Call) Run(run func(name string, bs *blobstore.File)) *MockFileBlobStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *blobstore.File
		if args[1] != nil {
			arg1 = args[1].(*blobstore.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileBlobStore_Update_Call) Return(err error) *MockFileBlobStore_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileBlobStore_Update_Call) RunAndReturn(run func(name string, bs *blobstore.File) error) *MockFileBlobStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
