// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/epam/edp-nexus-operator/pkg/client/nexus"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNexusCleanupPolicyManager creates a new instance of MockNexusCleanupPolicyManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNexusCleanupPolicyManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNexusCleanupPolicyManager {
	mock := &MockNexusCleanupPolicyManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNexusCleanupPolicyManager is an autogenerated mock type for the NexusCleanupPolicyManager type
type MockNexusCleanupPolicyManager struct {
	mock.Mock
}

type MockNexusCleanupPolicyManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNexusCleanupPolicyManager) EXPECT() *MockNexusCleanupPolicyManager_Expecter {
	return &MockNexusCleanupPolicyManager_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockNexusCleanupPolicyManager
func (_mock *MockNexusCleanupPolicyManager) Create(ctx context.Context, policy *nexus.NexusCleanupPolicy) error {
	ret := _mock.Called(ctx, policy)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *nexus.NexusCleanupPolicy) error); ok {
		r0 = returnFunc(ctx, policy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNexusCleanupPolicyManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNexusCleanupPolicyManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - policy *nexus.NexusCleanupPolicy
func (_e *MockNexusCleanupPolicyManager_Expecter) Create(ctx interface{}, policy interface{}) *MockNexusCleanupPolicyManager_Create_Call {
	return &MockNexusCleanupPolicyManager_Create_Call{Call: _e.mock.On("Create", ctx, policy)}
}

func (_c *MockNexusCleanupPolicyManager_Create_Call) Run(run func(ctx context.Context, policy *nexus.NexusCleanupPolicy)) *MockNexusCleanupPolicyManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *nexus.NexusCleanupPolicy
		if args[1] != nil {
			arg1 = args[1].(*nexus.NexusCleanupPolicy)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNexusCleanupPolicyManager_Create_Call) Return(err error) *MockNexusCleanupPolicyManager_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNexusCleanupPolicyManager_Create_Call) RunAndReturn(run func(ctx context.Context, policy *nexus.NexusCleanupPolicy) error) *MockNexusCleanupPolicyManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockNexusCleanupPolicyManager
func (_mock *MockNexusCleanupPolicyManager) Delete(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNexusCleanupPolicyManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNexusCleanupPolicyManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockNexusCleanupPolicyManager_Expecter) Delete(ctx interface{}, name interface{}) *MockNexusCleanupPolicyManager_Delete_Call {
	return &MockNexusCleanupPolicyManager_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockNexusCleanupPolicyManager_Delete_Call) Run(run func(ctx context.Context, name string)) *MockNexusCleanupPolicyManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNexusCleanupPolicyManager_Delete_Call) Return(err error) *MockNexusCleanupPolicyManager_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNexusCleanupPolicyManager_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockNexusCleanupPolicyManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockNexusCleanupPolicyManager
func (_mock *MockNexusCleanupPolicyManager) Get(ctx context.Context, name string) (*nexus.NexusCleanupPolicy, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *nexus.NexusCleanupPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*nexus.NexusCleanupPolicy, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *nexus.NexusCleanupPolicy); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nexus.NexusCleanupPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNexusCleanupPolicyManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockNexusCleanupPolicyManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockNexusCleanupPolicyManager_Expecter) Get(ctx interface{}, name interface{}) *MockNexusCleanupPolicyManager_Get_Call {
	return &MockNexusCleanupPolicyManager_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockNexusCleanupPolicyManager_Get_Call) Run(run func(ctx context.Context, name string)) *MockNexusCleanupPolicyManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNexusCleanupPolicyManager_Get_Call) Return(nexusCleanupPolicy *nexus.NexusCleanupPolicy, err error) *MockNexusCleanupPolicyManager_Get_Call {
	_c.Call.Return(nexusCleanupPolicy, err)
	return _c
}

func (_c *MockNexusCleanupPolicyManager_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (*nexus.NexusCleanupPolicy, error)) *MockNexusCleanupPolicyManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockNexusCleanupPolicyManager
func (_mock *MockNexusCleanupPolicyManager) Update(ctx context.Context, name string, policy *nexus.NexusCleanupPolicy) error {
	ret := _mock.Called(ctx, name, policy)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *nexus.NexusCleanupPolicy) error); ok {
		r0 = returnFunc(ctx, name, policy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNexusCleanupPolicyManager_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockNexusCleanupPolicyManager_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - policy *nexus.NexusCleanupPolicy
func (_e *MockNexusCleanupPolicyManager_Expecter) Update(ctx interface{}, name interface{}, policy interface{}) *MockNexusCleanupPolicyManager_Update_Call {
	return &MockNexusCleanupPolicyManager_Update_Call{Call: _e.mock.On("Update", ctx, name, policy)}
}

func (_c *MockNexusCleanupPolicyManager_Update_Call) Run(run func(ctx context.Context, name string, policy *nexus.NexusCleanupPolicy)) *MockNexusCleanupPolicyManager_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *nexus.NexusCleanupPolicy
		if args[2] != nil {
			arg2 = args[2].(*nexus.NexusCleanupPolicy)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNexusCleanupPolicyManager_Update_Call) Return(err error) *MockNexusCleanupPolicyManager_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNexusCleanupPolicyManager_Update_Call) RunAndReturn(run func(ctx context.Context, name string, policy *nexus.NexusCleanupPolicy) error) *MockNexusCleanupPolicyManager_Update_Call {
	_c.Call.Return(run)
	return _c
}
