// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/datadrivers/go-nexus-client/nexus3/schema/security"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUser creates a new instance of MockUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUser {
	mock := &MockUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUser is an autogenerated mock type for the User type
type MockUser struct {
	mock.Mock
}

type MockUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUser) EXPECT() *MockUser_Expecter {
	return &MockUser_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type MockUser
func (_mock *MockUser) ChangePassword(id string, password string) error {
	ret := _mock.Called(id, password)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(id, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUser_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockUser_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - id string
//   - password string
func (_e *MockUser_Expecter) ChangePassword(id interface{}, password interface{}) *MockUser_ChangePassword_Call {
	return &MockUser_ChangePassword_Call{Call: _e.mock.On("ChangePassword", id, password)}
}

func (_c *MockUser_ChangePassword_Call) Run(run func(id string, password string)) *MockUser_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUser_ChangePassword_Call) Return(err error) *MockUser_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUser_ChangePassword_Call) RunAndReturn(run func(id string, password string) error) *MockUser_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockUser
func (_mock *MockUser) Create(user security.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(security.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUser_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUser_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user security.User
func (_e *MockUser_Expecter) Create(user interface{}) *MockUser_Create_Call {
	return &MockUser_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *MockUser_Create_Call) Run(run func(user security.User)) *MockUser_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 security.User
		if args[0] != nil {
			arg0 = args[0].(security.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUser_Create_Call) Return(err error) *MockUser_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUser_Create_Call) RunAndReturn(run func(user security.User) error) *MockUser_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUser
func (_mock *MockUser) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUser_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUser_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockUser_Expecter) Delete(id interface{}) *MockUser_Delete_Call {
	return &MockUser_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockUser_Delete_Call) Run(run func(id string)) *MockUser_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUser_Delete_Call) Return(err error) *MockUser_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUser_Delete_Call) RunAndReturn(run func(id string) error) *MockUser_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockUser
func (_mock *MockUser) Get(id string) (*security.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *security.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*security.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *security.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*security.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUser_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUser_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockUser_Expecter) Get(id interface{}) *MockUser_Get_Call {
	return &MockUser_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockUser_Get_Call) Run(run func(id string)) *MockUser_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUser_Get_Call) Return(user *security.User, err error) *MockUser_Get_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUser_Get_Call) RunAndReturn(run func(id string) (*security.User, error)) *MockUser_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUser
func (_mock *MockUser) Update(id string, user security.User) error {
	ret := _mock.Called(id, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, security.User) error); ok {
		r0 = returnFunc(id, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUser_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUser_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id string
//   - user security.User
func (_e *MockUser_Expecter) Update(id interface{}, user interface{}) *MockUser_Update_Call {
	return &MockUser_Update_Call{Call: _e.mock.On("Update", id, user)}
}

func (_c *MockUser_Update_Call) Run(run func(id string, user security.User)) *MockUser_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 security.User
		if args[1] != nil {
			arg1 = args[1].(security.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUser_Update_Call) Return(err error) *MockUser_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUser_Update_Call) RunAndReturn(run func(id string, user security.User) error) *MockUser_Update_Call {
	_c.Call.Return(run)
	return _c
}
