// Code generated by mockery v2.15.0. DO NOT EDIT.

package openshift

import (
	context "context"

	appsv1 "github.com/openshift/api/apps/v1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	mock "github.com/stretchr/testify/mock"

	types "k8s.io/apimachinery/pkg/types"

	v1 "github.com/openshift/client-go/apps/applyconfigurations/apps/v1"

	v1beta1 "k8s.io/api/extensions/v1beta1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// DeploymentConfigInterface is an autogenerated mock type for the DeploymentConfigInterface type
type DeploymentConfigInterface struct {
	mock.Mock
}

// Apply provides a mock function with given fields: ctx, deploymentConfig, opts
func (_m *DeploymentConfigInterface) Apply(ctx context.Context, deploymentConfig *v1.DeploymentConfigApplyConfiguration, opts metav1.ApplyOptions) (*appsv1.DeploymentConfig, error) {
	ret := _m.Called(ctx, deploymentConfig, opts)

	var r0 *appsv1.DeploymentConfig
	if rf, ok := ret.Get(0).(func(context.Context, *v1.DeploymentConfigApplyConfiguration, metav1.ApplyOptions) *appsv1.DeploymentConfig); ok {
		r0 = rf(ctx, deploymentConfig, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appsv1.DeploymentConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.DeploymentConfigApplyConfiguration, metav1.ApplyOptions) error); ok {
		r1 = rf(ctx, deploymentConfig, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApplyStatus provides a mock function with given fields: ctx, deploymentConfig, opts
func (_m *DeploymentConfigInterface) ApplyStatus(ctx context.Context, deploymentConfig *v1.DeploymentConfigApplyConfiguration, opts metav1.ApplyOptions) (*appsv1.DeploymentConfig, error) {
	ret := _m.Called(ctx, deploymentConfig, opts)

	var r0 *appsv1.DeploymentConfig
	if rf, ok := ret.Get(0).(func(context.Context, *v1.DeploymentConfigApplyConfiguration, metav1.ApplyOptions) *appsv1.DeploymentConfig); ok {
		r0 = rf(ctx, deploymentConfig, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appsv1.DeploymentConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.DeploymentConfigApplyConfiguration, metav1.ApplyOptions) error); ok {
		r1 = rf(ctx, deploymentConfig, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, deploymentConfig, opts
func (_m *DeploymentConfigInterface) Create(ctx context.Context, deploymentConfig *appsv1.DeploymentConfig, opts metav1.CreateOptions) (*appsv1.DeploymentConfig, error) {
	ret := _m.Called(ctx, deploymentConfig, opts)

	var r0 *appsv1.DeploymentConfig
	if rf, ok := ret.Get(0).(func(context.Context, *appsv1.DeploymentConfig, metav1.CreateOptions) *appsv1.DeploymentConfig); ok {
		r0 = rf(ctx, deploymentConfig, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appsv1.DeploymentConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *appsv1.DeploymentConfig, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, deploymentConfig, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *DeploymentConfigInterface) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *DeploymentConfigInterface) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *DeploymentConfigInterface) Get(ctx context.Context, name string, opts metav1.GetOptions) (*appsv1.DeploymentConfig, error) {
	ret := _m.Called(ctx, name, opts)

	var r0 *appsv1.DeploymentConfig
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *appsv1.DeploymentConfig); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appsv1.DeploymentConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetScale provides a mock function with given fields: ctx, deploymentConfigName, options
func (_m *DeploymentConfigInterface) GetScale(ctx context.Context, deploymentConfigName string, options metav1.GetOptions) (*v1beta1.Scale, error) {
	ret := _m.Called(ctx, deploymentConfigName, options)

	var r0 *v1beta1.Scale
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *v1beta1.Scale); ok {
		r0 = rf(ctx, deploymentConfigName, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.Scale)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, deploymentConfigName, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Instantiate provides a mock function with given fields: ctx, deploymentConfigName, deploymentRequest, opts
func (_m *DeploymentConfigInterface) Instantiate(ctx context.Context, deploymentConfigName string, deploymentRequest *appsv1.DeploymentRequest, opts metav1.CreateOptions) (*appsv1.DeploymentConfig, error) {
	ret := _m.Called(ctx, deploymentConfigName, deploymentRequest, opts)

	var r0 *appsv1.DeploymentConfig
	if rf, ok := ret.Get(0).(func(context.Context, string, *appsv1.DeploymentRequest, metav1.CreateOptions) *appsv1.DeploymentConfig); ok {
		r0 = rf(ctx, deploymentConfigName, deploymentRequest, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appsv1.DeploymentConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *appsv1.DeploymentRequest, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, deploymentConfigName, deploymentRequest, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *DeploymentConfigInterface) List(ctx context.Context, opts metav1.ListOptions) (*appsv1.DeploymentConfigList, error) {
	ret := _m.Called(ctx, opts)

	var r0 *appsv1.DeploymentConfigList
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *appsv1.DeploymentConfigList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appsv1.DeploymentConfigList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *DeploymentConfigInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*appsv1.DeploymentConfig, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *appsv1.DeploymentConfig
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) *appsv1.DeploymentConfig); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appsv1.DeploymentConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rollback provides a mock function with given fields: ctx, deploymentConfigName, deploymentConfigRollback, opts
func (_m *DeploymentConfigInterface) Rollback(ctx context.Context, deploymentConfigName string, deploymentConfigRollback *appsv1.DeploymentConfigRollback, opts metav1.CreateOptions) (*appsv1.DeploymentConfig, error) {
	ret := _m.Called(ctx, deploymentConfigName, deploymentConfigRollback, opts)

	var r0 *appsv1.DeploymentConfig
	if rf, ok := ret.Get(0).(func(context.Context, string, *appsv1.DeploymentConfigRollback, metav1.CreateOptions) *appsv1.DeploymentConfig); ok {
		r0 = rf(ctx, deploymentConfigName, deploymentConfigRollback, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appsv1.DeploymentConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *appsv1.DeploymentConfigRollback, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, deploymentConfigName, deploymentConfigRollback, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, deploymentConfig, opts
func (_m *DeploymentConfigInterface) Update(ctx context.Context, deploymentConfig *appsv1.DeploymentConfig, opts metav1.UpdateOptions) (*appsv1.DeploymentConfig, error) {
	ret := _m.Called(ctx, deploymentConfig, opts)

	var r0 *appsv1.DeploymentConfig
	if rf, ok := ret.Get(0).(func(context.Context, *appsv1.DeploymentConfig, metav1.UpdateOptions) *appsv1.DeploymentConfig); ok {
		r0 = rf(ctx, deploymentConfig, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appsv1.DeploymentConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *appsv1.DeploymentConfig, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, deploymentConfig, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateScale provides a mock function with given fields: ctx, deploymentConfigName, scale, opts
func (_m *DeploymentConfigInterface) UpdateScale(ctx context.Context, deploymentConfigName string, scale *v1beta1.Scale, opts metav1.UpdateOptions) (*v1beta1.Scale, error) {
	ret := _m.Called(ctx, deploymentConfigName, scale, opts)

	var r0 *v1beta1.Scale
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1beta1.Scale, metav1.UpdateOptions) *v1beta1.Scale); ok {
		r0 = rf(ctx, deploymentConfigName, scale, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.Scale)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *v1beta1.Scale, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, deploymentConfigName, scale, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, deploymentConfig, opts
func (_m *DeploymentConfigInterface) UpdateStatus(ctx context.Context, deploymentConfig *appsv1.DeploymentConfig, opts metav1.UpdateOptions) (*appsv1.DeploymentConfig, error) {
	ret := _m.Called(ctx, deploymentConfig, opts)

	var r0 *appsv1.DeploymentConfig
	if rf, ok := ret.Get(0).(func(context.Context, *appsv1.DeploymentConfig, metav1.UpdateOptions) *appsv1.DeploymentConfig); ok {
		r0 = rf(ctx, deploymentConfig, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appsv1.DeploymentConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *appsv1.DeploymentConfig, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, deploymentConfig, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *DeploymentConfigInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	var r0 watch.Interface
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDeploymentConfigInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeploymentConfigInterface creates a new instance of DeploymentConfigInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeploymentConfigInterface(t mockConstructorTestingTNewDeploymentConfigInterface) *DeploymentConfigInterface {
	mock := &DeploymentConfigInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
