// Code generated by mockery v2.9.4. DO NOT EDIT.

package openshift

import (
	mock "github.com/stretchr/testify/mock"
	rest "k8s.io/client-go/rest"

	v1 "github.com/openshift/client-go/route/clientset/versioned/typed/route/v1"
)

// RouteV1Client is an autogenerated mock type for the RouteV1Client type
type RouteV1Client struct {
	mock.Mock
}

// RESTClient provides a mock function with given fields:
func (_m *RouteV1Client) RESTClient() rest.Interface {
	ret := _m.Called()

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// Routes provides a mock function with given fields: namespace
func (_m *RouteV1Client) Routes(namespace string) v1.RouteInterface {
	ret := _m.Called(namespace)

	var r0 v1.RouteInterface
	if rf, ok := ret.Get(0).(func(string) v1.RouteInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.RouteInterface)
		}
	}

	return r0
}
